version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-
      - run:
          name: GServices
          command: echo $GSERVICES | base64 --decode > google-services.json
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-
          paths:
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_artifacts:
          path: .circle/
          destination: reports
      - store_test_results:
          path: .circle/test-results
